// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU6yxcuQ7upMg0AHQPl7Tde1xSSJPtNNc',
    appId: '1:286052176659:web:61246e61a6e476493200e6',
    messagingSenderId: '286052176659',
    projectId: 'medics-3f2c6',
    authDomain: 'medics-3f2c6.firebaseapp.com',
    storageBucket: 'medics-3f2c6.firebasestorage.app',
    measurementId: 'G-W1LHQP95X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwdDk-HgCqqZ8nzi29c_x8YsM2HrMLj4',
    appId: '1:286052176659:android:c7cf33b894d65bfa3200e6',
    messagingSenderId: '286052176659',
    projectId: 'medics-3f2c6',
    storageBucket: 'medics-3f2c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkVC5agHiui9JCseQegUi87LM0ktjLSc',
    appId: '1:286052176659:ios:9456606b1cb231383200e6',
    messagingSenderId: '286052176659',
    projectId: 'medics-3f2c6',
    storageBucket: 'medics-3f2c6.firebasestorage.app',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVkVC5agHiui9JCseQegUi87LM0ktjLSc',
    appId: '1:286052176659:ios:9456606b1cb231383200e6',
    messagingSenderId: '286052176659',
    projectId: 'medics-3f2c6',
    storageBucket: 'medics-3f2c6.firebasestorage.app',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU6yxcuQ7upMg0AHQPl7Tde1xSSJPtNNc',
    appId: '1:286052176659:web:9f1d9abae80622a53200e6',
    messagingSenderId: '286052176659',
    projectId: 'medics-3f2c6',
    authDomain: 'medics-3f2c6.firebaseapp.com',
    storageBucket: 'medics-3f2c6.firebasestorage.app',
    measurementId: 'G-L8840P4JRJ',
  );
}
