name: medical
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.12.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0
  rounded_loading_button: ^2.1.0
  responsive_sizer: ^3.1.1
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.0.9
  flutter_chat_ui: ^1.6.9
  animated_bottom_navigation_bar: ^1.2.0
  path_provider_windows: ^2.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.5
  firebase_crashlytics: ^4.3.5
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - images/google.png
    - images/apple.png
    - images/facebook.png
    - images/article1.png
    - images/capsules.png
    - images/capsules2.png
    - images/
    - lib/icons/
